language: go

go:
  - 1.9.x
  - "1.10.x"
before_install:
  - go get -v github.com/dollarshaveclub/line
  - go get -v github.com/sirupsen/logrus
  - go get -v github.com/stretchr/testify/assert

script:
  - go test ./...